### ISSUE TITLE
Clone failed on Windows

### ISSUE THREAD

**Issue by Verf** [phaazon/mind.nvim#16]
File `.mind/data/20220811172228-Insert Mind* highlight.md` is a invalid file name on Windows system, that will cause the clone failed.

![Snipaste_2022-08-22_09-02-23](https://user-images.githubusercontent.com/22053969/185819855-9425e2a7-0b2d-464b-b2d5-991a1653b50f.png)

I found some [solution](https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows), but can't solve the problem perfectly. Therefore, the best method is, please rename the file :).

**Comment by phaazon** [comment]
Ah. Yeah, I need a « clean node paths » before creating data files. Thanks for opening the issue.

**Comment by phaazon** [comment]
Also, now that I think about it, I should probably move that tree in my space, since the plugin is downloaded by other people.

**Comment by phaazon** [comment]
@Verf please tell me whether it’s okay now. The fix is not yet released as part of a version, but you can use `master`.

**Comment by Verf** [comment]
> @Verf please tell me whether it’s okay now. The fix is not yet released as part of a version, but you can use `master`.

It's ok now 😃
