### ISSUE TITLE
Undocumented dependency: window-picker

### ISSUE THREAD

**Issue by aerosol** [phaazon/mind.nvim#17]
Looks like installing https://github.com/s1n7ax/nvim-window-picker makes it possible to open nodes, otherwise a stack trace is shown.

**Comment by phaazon** [comment]
Yeah, I need to figure a solution on what I want to do here. Maybe just opening a split or the « last buffer » would be enough, so that I can drop the dependency. Or does Neovim have something `vim.ui`?

**Comment by ofirgall** [comment]
Its ok to have a requirements, you want re-use good code it's just need to be documented as part of `Installation`.
E.g:
```lua
use {
	'phaazon/mind.nvim',
	tag = "v2.*",
	requires = { 's1n7ax/nvim-window-picker', tag = 'v1.*' }
}
```

**Comment by phaazon** [comment]
Yeah, but the thing is, I’m not sure I want to have a dependency on such a specific implementation. People might want to use something else. I don’t have a good solution to this problem, I think another plugin is needed to define the interface (i.e. pick a window) and let people pick the implementation they want.

**Comment by ofirgall** [comment]
Right now as a user you install a plugin, try to use it, gets a big error prompt that doesn't imply that you **have** to install a requirement too, until its a requirement it's must to be part of the readme

**Comment by phaazon** [comment]
@ofirgall I agreed it should have been part of it. But it’s better to remove the requirement for now. I want to have an interface plugin before using such a feature again. It was there because I was writing the plugin with that feature on (I already use it elsewhere), but people might want to use something else.
