### ISSUE TITLE
Local project doesnt work if neovim opened from another directory

### ISSUE THREAD

**Issue by sawwheet** [phaazon/mind.nvim#23]
First of want to say that i really think this plugin has a lot of potential for me. Thank you for your work on it!

My workflow usually consists of opening neovim from whatever directory i happen to be in at the time, and then using `project.nvim` to navigate to a project. 

I have noticed 2 things that might happen with this workflow:

1. `mind.nvim` seems to keep the wd as wherever i opened neovim from. 
2. My local project state gets wiped

To expand on item 1 -- I will open neovim from my home directory, navigate to some project, call `MindOpenProject`, and it names the 'mind' to what the directory i opened it from was (and as such wiping all 'nodes' i created)

To expand on item 2 -- It will properly notice my project, but my previous state is wiped and all nodes are gone

sorry if this is not enough info, let me know if i can provide more

as a workaround for now, I am putting everything in the main node as sub nodes

**Comment by phaazon** [comment]
Hello,

Mind uses the `getcwd()` function. However, maybe that the state should be loaded every time the tree is opened, indeed. So that if you change directory, it will follow it. The fix is trivial, I will work on that today.

**Comment by sawwheet** [comment]
thank you!

**Comment by phaazon** [comment]
A workaround is to call `MindReloadState` after you have moved. It should reload the state if the CWD is correctly changed.

I’m currently fixing it.

**Comment by phaazon** [comment]
Should be fixed now, please let me know what you think @sawwheet. I also included a guard if you `cd` without closing an open local tree; it will be forbidden and a notfication explaining how to solve the problem will be displayed.

**Comment by sawwheet** [comment]
Works great!

I tested by switching between 2 different projects in one neovim session. Opening the local mind worked as expected when moving back and forth.

I also got the guard you mentioned when trying to update the state for one mind when not in the correct working directory. 

thank you very much

**Comment by phaazon** [comment]
You’re very welcome! :slightly_smiling_face:
