### ISSUE TITLE
[New Feature] `change_icon_menu`

### ISSUE THREAD

**Issue by ofirgall** [phaazon/mind.nvim#24]
I think a preset of a configurable icons would be useful, a command like `change_icon` should be added.
`change_icon_menu` - open the preset icon menu with `vim.ui.select` and set the chosen icon, names for the icons would be great too!

**Comment by phaazon** [comment]
Hm, I don’t think that’s going to be possible, because those « predefined icons » depend greatly on the workflow of people.

However, it could be interesting to add that as a config option. It would have a couple of defaults one but people could override them in their configuration. That could be an interesting thing indeed.

**Comment by ofirgall** [comment]
> However, it could be interesting to add that as a config option. It would have a couple of defaults one but people could override them in their configuration. That could be an interesting thing indeed.
That's what I meant by `preset of a configurable icons`.
Just to clarify how I see that.
```lua
require('mind').setup{
      preset_icons = {
              ["Task"] = "⚐"
      }
}
```

**Comment by phaazon** [comment]
Yep. Should be quite easy to implement then. I’ll see that later today or tomorrow.

**Comment by phaazon** [comment]
Current state:

![a](https://user-images.githubusercontent.com/506592/186408437-b560374f-37bb-4ed8-bd9f-57ab3d16aaf6.png)

![b](https://user-images.githubusercontent.com/506592/186408431-66c45979-527f-48a9-9307-f547fc9f5f84.png)

![c](https://user-images.githubusercontent.com/506592/186408428-9c53d0d0-1272-4a01-95a8-f3d17d3aa581.png)

**Comment by phaazon** [comment]
I’m merging that to `master` after my lunch break. :slightly_smiling_face:

**Comment by ofirgall** [comment]
looks amazing! thanks for this great plugin, very appreciated.
