### ISSUE TITLE
mind.json formatting

### ISSUE THREAD

**Issue by usmcamp0811** [phaazon/mind.nvim#45]
I have found if I format the `mind.json` file that it breaks the plugin. By default the JSON is a single line which is hard to read. If you format it with Prettier so its more human readable things wig out with the below error. 

```
Error executing Lua callback: ...nvim/site/pack/packer/start/mind.nvim/lua/mind/state.lua:59: Expected object key string but found T_END at character 2
stack traceback:
        [C]: in function 'decode'
        ...nvim/site/pack/packer/start/mind.nvim/lua/mind/state.lua:59: in function 'load_main_state'
        .../nvim/site/pack/packer/start/mind.nvim/lua/mind/init.lua:103: in function 'wrap_main_tree_fn'
        .../nvim/site/pack/packer/start/mind.nvim/lua/mind/init.lua:60: in function 'open_main'
        .../nvim/site/pack/packer/start/mind.nvim/lua/mind/init.lua:14: in function <.../nvim/site/pack/packer/start/mind.nvim/lua/mind/init.lua:13>
Press ENTER or type command to continue
```

I made no changes to the file other than moving things to multiple lines.

**Comment by diego-rapoport** [comment]
I just had the same error with `T_END` , but stack traceback is a bit different and the line of `state.lua`.

**Comment by phaazon** [comment]
Yep, I had that problem too and notified the Neovim people. They told me it works on their side, so I don’t have any workaround. :disappointed:
