### ISSUE TITLE
[Bug] Can't update mind.nvim, `.mind/state.json` is dirty

### ISSUE THREAD

**Issue by ofirgall** [phaazon/mind.nvim#47]
Because of `.mind/state.json/` that resides inside the git repo of `mind.nvim` packer failed to update the plugin I had to manually reset the repo before updating

**Comment by phaazon** [comment]
Ah that’s unfortunate, thanks for notifying. Did you try to open that tree? If not, maybe there was a rebase on `master` at some point, not quite sure. That shouldn’t happen normally.

**Comment by ofirgall** [comment]
I didn't try to open the tree, stashed it, updated the plugin tried to pop it it caused conflicts, after that I hard restored to the update head.
