### ISSUE TITLE
Mind window won't open after closing it 

### ISSUE THREAD

**Issue by caenrique** [phaazon/mind.nvim#53]
Both the user command `:MindOpenMain` and the Lua api `require('mind').open_main()` won't do anything after the first time.

eg:

- open the mind tree with `:MindOpenMain` -> the mind tree is opened
- Close the window with `:q` -> the window is closed
- call `:MindOpenMain` again -> Nothing happens

I have the V2 tag setup with packer and I'm using neovim v0.8.0-dev on MacOS

**Comment by phaazon** [comment]
Yep, that’s a known bug. You need to close the window with `q`. I think the fix is trivial but I need to be sure how to do it correctly.
