### ISSUE TITLE
Cannot reopen `:MindOpenProject`

### ISSUE THREAD

**Issue by cybergsus** [phaazon/mind.nvim#55]
When I do `:MindOpenProject` and then close the buffer with `ZZ` or `:q`, `:MindOpenProject` stops working until I reopen neovim. Maybe it's not registering when the buffer gets closed and still thinks the buffer is open.

Here is a run of `nvim --version` in case you need more information. Btw, great work! I finally found something I could use to organize myself that wasn't too complex to use :)

```
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/lib64/ccache/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/gsus/tools/neovim/build/config -I/home/gsus/tools/neovim/src -I/home/gsus/tools/neovim/.deps/usr/include -I/usr/include -I/home/gsus/tools/neovim/build/src/nvim/auto -I/home/gsus/tools/neovim/build/include
Compiled by gsus@cyclone

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/gsus/.local/share/nvim"

Run :checkhealth for more info
```

**Comment by phaazon** [comment]
Which version of mind are you using? I fixed that a couple of days ago on `master`.

**Comment by peter-lyr** [comment]
I encounter this problem too when I type `:MindOpenProject<CR>` on any buffer.

![image](https://user-images.githubusercontent.com/55801796/214228784-7147d7e7-e350-4931-b12a-5da188b5cf1e.png)

![image](https://user-images.githubusercontent.com/55801796/214230752-d0314bd9-082a-46ef-b3c5-7d51e34dc42c.png)
