### ISSUE TITLE
Forbidden node creation

### ISSUE THREAD

**Issue by simondrake** [phaazon/mind.nvim#57]
**Just** installed this plugin to see if I could use it for note-taking, but am failing at the first hurdle and am getting a `forbidden node creation` error.

### Steps to reproduce

1. Open neovim (`nvim`)
2. Open mind (`MindOpenMain`)
3. Start a new line (`o`)
4. Mind requests a node name - I've tried `scratch`, `test`, `random` 
5. See that there is an error - `forbidden node creation`

![image](https://user-images.githubusercontent.com/62928647/188434358-a6a92b88-6e76-4ccb-9911-2af5c851d630.png)

Saw a similar issue (#44), where the OP resolved the issue by setting `modifiable` (`:set ma`), but that doesn't fix the issue.

**Comment by simondrake** [comment]
I just tried `I` as opposed to `o`, which asks me for a node name and doesn't return an error - but nothing actually changes and I still can't create a new node. 

I have the same problem when opening with `MindOpenSmartProject`.

There doesn't seem to be a quick-start anywhere, so it's not immediately clear what steps are needed to get this working.

**Comment by jweickm** [comment]
Glad to hear it worked.
