### ISSUE TITLE
Use relative path for nodes

### ISSUE THREAD

**Issue by Palpatineli** [phaazon/mind.nvim#59]
When persistence.data_dir is set like '\~/note' for the master note, it's expanded first and the full path is saved to the state file when a node is created. Thus when the master note folder is moved between computers with different user names, the previous node files cannot be opened. Can you modify the save process so the path of a node is relative to the user folder, for example, '\~/note/202209131238-note-1.md'?

**Comment by phaazon** [comment]
This is currently not planned. You will have to modify the paths manually when doing so, or use local trees.

Alternatively, you can open a PR that does the `expand` on the fly but that’s a bit of work and I don’t intend working on that.
