### ISSUE TITLE
Global project doesn't work

### ISSUE THREAD

**Issue by mostafaqanbaryan** [phaazon/mind.nvim#64]
Hi,
Using `:MindProjectOpen global`, works based on `cwd` and creates a new project separately.
So now, I don't have access to my last project that was global.

To reproduce:
Open `vim` inside a directory and with `:MindProjectOpen global`, open a new project.
After adding a node or two, close vim.
Now open `vim` inside another directory and call the command again.
You should see the message: `creating a new global project tree`

**Comment by phaazon** [comment]
I don’t reproduce and I’m not sure you’re using it the right way. If you change directory, it will create another global project tree, as intended.
