### ISSUE TITLE
Syncing?

### ISSUE THREAD

**Issue by aasutossh** [phaazon/mind.nvim#69]
To mobile devices/private servers (maybe just for viewing or backup)?

**Comment by PlanAborted** [comment]
For backup I guess you can change `persistence.state_path` and `persistence.data_dir` to a cloud based folder (like a Google Drive synced folder on your system).
By doing that you could also edit content of data files associated to nodes.

**Comment by phaazon** [comment]
Yep, I do that with git and jobs. I don’t plan on supporting syncing, at least not for a long time.
