### ISSUE TITLE
(Philosophy question) I see when I create a local tree, there is a `.mind` folder, why not store all the tree in one directory?

### ISSUE THREAD

**Issue by aasutossh** [phaazon/mind.nvim#70]
Or could you elaborate the working of `mind.nvim`, if you could?

**Comment by phaazon** [comment]
A local tree is by definition local, so `.mind` has to be in the local directory.

You can have a project, CWD-based tree that is stored globally by passing the `global` argument to either `:MindOpenProject` or `:MindOpenSmartProject`’s prompt.
