### ISSUE TITLE
KEYBINDING HELP for fuzzy search

### ISSUE THREAD

**Issue by novicebaba** [phaazon/mind.nvim#86]
@phaazon, can you share your key binding for the fuzzy search? I tried a lot of options but could not get it to work...

**Comment by a0x77ry** [comment]
> @phaazon, can you share your key binding for the fuzzy search? I tried a lot of options but could not get it to work...

@novicebaba Have you tried Shift + Enter while being on the tree window?

**Comment by novicebaba** [comment]
@a0x77ry , when I do "Shift + Enter" from the tree window, it just opens up the note.. It does not open up the fuzzy search.. I'm assuming I need to setup something with the "mind.indexing.search_index()" API. but I'm not completely clear on how. I dont see any examples in the doc

**Comment by novicebaba** [comment]
Thanks a ton @a0x77ry .
Doing the keymaps setup that you showed worked in a way. Now I do see that the index is shown. However, it does not come up as a pop up. It comes at the bottom of the screen where the command mode prompt is. And it does not give me an option to fuzzy search. It asks me to select by typing the number or clicking with the mouse. 
![Screenshot 2023-01-11 at 10 42 55 AM](https://user-images.githubusercontent.com/89361162/211865029-1390dfb5-b5bd-4d9a-a8dc-f3e47c3a99fd.png)

**Comment by a0x77ry** [comment]
@novicebaba that's because you don't have telescope.nvim installed. You'll need it for the pop up (and probably telescope-ui-select.nvim too).

**Comment by novicebaba** [comment]
@a0x77ry , I do have telescope installed and I use it extensively.. Is there something that could be broken between mind.nvim & telescope ? Maybe something I need to do in the setup?

Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-telescope/telescope-fzy-native.nvim'
Plug 'nvim-telescope/telescope-fzf-native.nvim', {'do' : 'make'}
Plug 'nvim-telescope/telescope-file-browser.nvim'


This is how I setup mind based on your recommendation -

lua require('mind').setup {keymaps = {normal = { ["<leader>ms"] = "open_data_index" } } }

Btw, if I did not mention, thanks a ton for answering to all my posts :)

**Comment by novicebaba** [comment]
@a0x77ry .. It was missing telescope-ui-select.
Sorry, I missed that. Its working now.


Just one final question to complete the loop. Is the a way to launch the fuzzy search from a regular buffer. As of now, I've having to do it from the mind buffer, it would be great if we can fuzzy search from a regular file buffer.

Thanks for your help

**Comment by a0x77ry** [comment]
@novicebaba I haven't found any way to run the search from regular buffers. It may exist, but I'm not aware of it.

**Comment by novicebaba** [comment]
ok .. thanks @a0x77ry .. do let me know if you figure it out at some point.. closing the issue.. thanks for your support..
