### ISSUE TITLE
Error when saving mind data with custom path

### ISSUE THREAD

**Issue by tiagoprn** [phaazon/mind.nvim#89]
Hey @phaazon ! 

Amazing work on this plugin, I am excited to use it and have been making some experiments to see if I can embrace it on my workflow, and only one thing is stopping me from that. Let me elaborate. 

I customized the persistence path like e.g. below: 

``` lua
mind.setup({
	keymaps = { -- useful inside the tree window
		normal = {
			["ms"] = "open_data_index",
		},
	},

	persistence = {
		state_path = "/tmp/mindsandbox/",
		data_dir = "/tmp/mindsandbox/",
	},

	edit = {
		data_header = "# %s",
	},

	ui = {
		width = 50,
		icon_preset = {
			{ " ", "Sub-project" },
			{ " ", "Journal, newspaper, weekly and daily news" },
			{ " ", "For when you have an idea" },
			{ " ", "Note taking?" },
			{ "陼", "Task management" },
			{ " ", "Uncheck, empty square or backlog" },
			{ " ", "Full square or on-going" },
			{ " ", "Check or done" },
			{ " ", "Trash bin, deleted, cancelled, etc." },
			{ " ", "GitHub" },
			{ " ", "Monitoring" },
			{ " ", "Internet, Earth, everyone!" },
			{ " ", "Frozen, on-hold" },
		},
	},
})
```

I tried adding and removing the trailing slash, but both result on the error below: 

[Screenshot](https://s3.us-west-1.wasabisys.com/tiagoprnl-public/tiagoprnl_static/2023-01-25_19-12.png)

As you can see on the screenshot at the pane below, all is right on the filesystem (I thought permissions but discarded showing  the permissions on the directory path). 

Is there anything I am missing? Or can I get more details to allow me to inspect  e.g. changing log levels or using a "debug mode"? 

Thank you!

**Comment by dongdongbh** [comment]
Encountering same error

**Comment by rzabcio** [comment]
But... Shouldn't `state_paht` be point a JSON **file**, not dir?

**Comment by dongdongbh** [comment]
> But... Shouldn't `state_path` be pointing a JSON **file**, not dir?
> 
> For example I reversed basic logic, so data files are in main persistence dir and state in subdir, and it works:
> 
> ```
> require('mind').setup({
>   persistence = {
>     state_path = "~/vimwiki/default/.mind/mind.json",
>     data_dir = "~/vimwiki/default/",
>   },
> ```

Oh, yes, solved!

**Comment by tiagoprn** [comment]
It worked! I guess I have the word "path" on my mental model always associated with directories, but I am glad that it was so simple. Thank you @rzabcio !
